server:
  port: 80
---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: real
server:
  port: 8002
---
property:
      test:
        name: property depth test
propertyTest: test
propertyTestList: a,b,c


spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
